services:
  copilot:
    build: .
    container_name: python_app
    ports:
      - "8501:8501"
      - "8000:8000"
    # env_file:
    #   - .env
    volumes:
      - .:/app
    environment:
      DB_HOST: ${MYSQL_HOST}
      DB_PORT: ${MYSQL_PORT}
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
    depends_on:
      - mysql
    
  mysql:
    # platform: linux/amd64 
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - './docker/mysql/data:/var/lib/mysql'
      # - './docker/mysql/DB:/docker-entrypoint-initdb.d'
