services:
  copilot:
    build: .
    container_name: python_app
    ports:
      - "${APP_PORT}:8501"  # メインアプリ (app.py)
      - "${MGR_DASHBOARD_PORT}:8502"  # マネージャーダッシュボード (mgr_dashboard.py)
      - "${ADMIN_DASHBOARD_PORT}:8503"  # 管理者画面 (admin_dashboard.py)
      - "${APP_REGISTER_PORT}:8504"  # ユーザー登録 (app_register.py)
      - "${PROMPT_KEY_DASHBOARD_PORT}:8505"  # プロンプトキー管理 (prompt_key_dashboard.py)
      - "${API_PORT}:8000"  # API用
    # env_file:
    #   - .env
    volumes:
      - .:/app
    environment:
      DB_HOST: ${MYSQL_HOST}
      DB_PORT: ${MYSQL_PORT}
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
    depends_on:
      - mysql
    
  mysql:
    # platform: linux/amd64 
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - './docker/mysql/data:/var/lib/mysql'
      # - './docker/mysql/DB:/docker-entrypoint-initdb.d'
