score_items:
  - ヒアリング姿勢
  - 説明のわかりやすさ
  - クロージングの一貫性
  - 感情の乗せ方と誠実さ
  - 対話のテンポ

A_team:
  product: "新車サブスクリプション"
  text_prompt: |
    以下の会話内容を読み、次の5つの評価項目について10点満点で数値を出し、理由を含めてフィードバックを記載してください。

    【評価項目】
    ヒアリング姿勢:
    説明のわかりやすさ:
    クロージングの一貫性:
    感情の乗せ方と誠実さ:
    対話のテンポ:

    【強み】
    （顧客との関係構築・提案の明瞭性など）

    【改善点】
    （顧客の不安払拭・情報不足・説明不足の改善）

    【注意すべきポイント】
    （沈黙や遮り、不安感を与える対応など）

    【次に取るべき推奨アクション】
    - 
    - 
    - 
  audio_prompt: |
    以下は新車営業トークの音声特徴量です。
    声の大きさ・テンポ・沈黙・抑揚から営業スキルを5点満点で評価し、改善ポイントを簡潔に述べてください。
  notes: "若手が多いため、フィードバックは優しく具体的に。"

B_team:
  product: "中古車割賦販売"
  text_prompt: |
    以下の会話内容を読み、次の5つの評価項目について10点満点で数値を出し、理由を含めてフィードバックを記載してください。

    【評価項目】
    ヒアリング姿勢:
    説明のわかりやすさ:
    クロージングの一貫性:
    感情の乗せ方と誠実さ:
    対話のテンポ:

    【強み】
    （端的でわかりやすい説明、信頼を得た部分）

    【改善点】
    （説明の順序、端折りすぎ、不足した確認）

    【注意すべきポイント】
    （冗長な話、早口、遮り、機会損失）

    【次に取るべき推奨アクション】
    - 
    - 
    - 
  audio_prompt: |
    以下は中古車営業の音声ログです。
    ベテラン営業を想定し、無駄な沈黙や過剰なトークを減らす観点から評価し、
    声の質や速度などから5点満点でアドバイスしてください。
  notes: "ベテラン営業多め。短時間勝負。端的なFBが好まれる。"

C_team:
  product: "法人向けEVカーリース"
  text_prompt: |
    以下の会話内容を読み、次の5つの評価項目について10点満点で数値を出し、理由を含めてフィードバックを記載してください。

    【評価項目】
    ヒアリング姿勢:
    説明のわかりやすさ:
    クロージングの一貫性:
    感情の乗せ方と誠実さ:
    対話のテンポ:

    【強み】
    （論理性・要点明示・法人理解力）

    【改善点】
    （曖昧な説明・手戻り発生・比較資料不足）

    【注意すべきポイント】
    （プレゼンの論理順、資料説明の精度など）

    【次に取るべき推奨アクション】
    - 
    - 
    - 
  audio_prompt: |
    以下はEV商談時の音声特徴量です。
    論理的なトーンか、聞きやすい構成か、沈黙・詰まりのバランスを重視し、5点満点で評価してください。
  notes: "法人対応のため、トークの論理構造と要点整理が最重要。"

F_team:
  product: "新規・混在チーム"
  text_prompt: |
    以下の会話内容を読み、次の5つの評価項目について10点満点で数値を出し、理由を含めてフィードバックを記載してください。

    【評価項目】
    ヒアリング姿勢:
    説明のわかりやすさ:
    クロージングの一貫性:
    感情の乗せ方と誠実さ:
    対話のテンポ:

    【強み】
    （個性や工夫、顧客目線の工夫）

    【改善点】
    （話しすぎ、説明の過不足、曖昧な表現）

    【注意すべきポイント】
    （営業経験の浅さによる認識ギャップ）

    【次に取るべき推奨アクション】
    - 
    - 
    - 
  audio_prompt: |
    音声の抑揚や沈黙の使い方、声のトーンなどからトークの印象度を評価し、
    伝わりやすさや説得力について5点満点でアドバイスしてください。
  notes: "Fチームは幅広く混在しているため、柔軟かつバランス重視で評価してください。"
